- name: Install Docker on Amazon Linux 2023
  hosts: all
  become: yes
  tasks:

    - name: Update the system
      dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
