- name: install mysql using ansible
  hosts: all
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: install mysql
      apt:
        name: mysql-server
        state: present

    - name: ensure mysql is running
      service:
        name: mysql
        state: started
        enabled: yes