# Script for nginx server setup and git clone web
- name: Install Ansible on Amazon Linux 2023
  hosts: all
  become: yes
  tasks:
    - name: Install Ansible via DNF
      dnf:
        name: ansible
        state: present

    - name: Install Nginx Server
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Start the nginx Server
      service:
        name: nginx
        state: started
        enabled: yes

    - name: creating directory
      file:
        path: /usr/share/nginx/html
        state: directory

    - name: Install git
      dnf:
        name: git
        state: present

    - name: clone from git repo
      git:
        repo: https://github.com/Yogesh-sa1n1/portfolio.git
        dest: /usr/share/nginx/html/new
        version: main


#    - name: create custom index page
#     copy:
#        content: "<h1> ansible configure management</h1>"
#        dest: /usr/share/nginx/html/index.html


    - name: Restart nginx
      service:
        name: nginx
        state: restarted
