- name: Install Node.js and npm
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Add NodeSource Node.js 20.x setup script
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm explicitly
      apt:
        name: npm
        state: present

    - name: Check npm version
      command: npm --version
      register: npm_version
      changed_when: false