---
- name: Create a user on Linux systems
  hosts: all
  become: yes

  vars:
    new_user: devuser
    user_password: "{{ 'MySecureP@ssw0rd' | password_hash('sha512') }}"
    user_shell: /bin/bash

  tasks:
    - name: Create the user with a home directory and bash shell
      user:
        name: "{{ new_user }}"
        password: "{{ user_password }}"
        shell: "{{ user_shell }}"
        state: present
        create_home: yes

    - name: Add user to sudoers (optional)
      user:
        name: "{{ new_user }}"
        groups: sudo
        append: yes

